logging:
  level:
    root: info
    org.springframework.jdbc.core: trace
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:library;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    sql:
      init:
        mode: always
        data-locations: data.sql
        schema-locations: schema.sql
    h2:
      console:
        enabled: true
  shell:
    interactive:
      enabled: true